In [1]:
import pandas as pd

df = pd.read_csv('./dataset.csv')

In [2]:
df['Sr. No'] = df['Sr. No'].fillna(method='ffill')
grouped_df = df.groupby('Sr. No')
required_columns = ['Data'] + [f'Unnamed: {i}' for i in range(3, 10)]
processed_groups = {}
for name, group in grouped_df:
    missing_columns = [
        col for col in required_columns if col not in group.columns]
    if missing_columns:
        print(f"Missing columns in group {name}: {missing_columns}")
        continue
    filtered_group = group[required_columns]
    filtered_group.fillna('', inplace=True)
    processed_groups[name] = filtered_group
df.drop(columns=required_columns, inplace=True)
new_df = df.groupby('Sr. No').first()

for i in range(1, len(processed_groups) + 1):
    d = processed_groups[i]
    new_columns = d.iloc[0]
    d.columns = new_columns
    d = d.drop(d.index[0])
    d.reset_index(drop=True, inplace=True)
    d.replace("", float("NaN"), inplace=True)
    d.dropna(how='all', axis=1, inplace=True)
    d = d.drop(d.index[-1])
    processed_groups[i] = d

new_df = new_df.assign(Data=processed_groups.values())
df = new_df
df.head()

C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Sr. No'] = df['Sr. No'].fillna(method='ffill')
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  filtered_group.fillna('', inplace=True)
C:\Users\Aditya\AppData\Local\Temp\ipykernel_4932\115758980.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_group.fillna('', inplace=True)

,Questions,Alpha,Type,Data
Sr. No,,,,
1.0,A researcher is studying the effect of differe...,0.05,CRD,0 Fertilizer A Fertilizer B Fertilizer C 0 ...
2.0,A company wants to compare customer satisfacti...,0.01,CRD,7 Model X Model Y Model Z 0 7 8 ...
3.0,To study the effect of three different diets o...,0.05,CRD,14 Diet A Diet B Diet C 0 5 4 ...
4.0,The preference scores (out of 10) for three di...,0.05,FD,21 Market Market Packaging A Packaging B P...
5.0,The productivity (in units) for employees usin...,0.05,FD,29 Shift Shift Tool A Tool B Tool C 0 ...

In [3]:
df.reset_index(inplace=True)
df.drop(columns='Sr. No', inplace=True)
df.head()

,Questions,Alpha,Type,Data
0,A researcher is studying the effect of differe...,0.05,CRD,0 Fertilizer A Fertilizer B Fertilizer C 0 ...
1,A company wants to compare customer satisfacti...,0.01,CRD,7 Model X Model Y Model Z 0 7 8 ...
2,To study the effect of three different diets o...,0.05,CRD,14 Diet A Diet B Diet C 0 5 4 ...
3,The preference scores (out of 10) for three di...,0.05,FD,21 Market Market Packaging A Packaging B P...
4,The productivity (in units) for employees usin...,0.05,FD,29 Shift Shift Tool A Tool B Tool C 0 ...

In [4]:
print(df.iloc[9]['Data'])

66     1     2     3     4
0   6.33  6.26  6.44  6.29
1   6.26  6.36  6.38  6.23
2   6.31  6.23  6.58  6.19
3   6.29  6.27  6.54  6.21
4    6.4  6.19  6.56   NaN
5    NaN   6.5  6.34   NaN
6    NaN  6.19  6.58   NaN
7    NaN  6.22   NaN   NaN

In [5]:
df['rows'] = df['Data'].apply(lambda x: x.shape[0])
df['columns'] = df['Data'].apply(lambda x: x.shape[1])
df.head(10)

,Questions,Alpha,Type,Data,rows,columns
0,A researcher is studying the effect of differe...,0.05,CRD,0 Fertilizer A Fertilizer B Fertilizer C 0 ...,5,3
1,A company wants to compare customer satisfacti...,0.01,CRD,7 Model X Model Y Model Z 0 7 8 ...,5,3
2,To study the effect of three different diets o...,0.05,CRD,14 Diet A Diet B Diet C 0 5 4 ...,5,3
3,The preference scores (out of 10) for three di...,0.05,FD,21 Market Market Packaging A Packaging B P...,6,5
4,The productivity (in units) for employees usin...,0.05,FD,29 Shift Shift Tool A Tool B Tool C 0 ...,6,5
5,The effectiveness scores (out of 10) of differ...,0.05,FD,37 Platform Platform Ad Type 1 Ad Type 2 Ad T...,6,5
6,The wear of tires from three different brands ...,0.01,RBD,45 Supplier Speed 20 mph Speed 40 mph Speed 60...,5,4
7,The crop yield (in tons) for three types of fe...,0.01,RBD,52 Soil Type Fertilizer A Fertilizer B Fertili...,5,4
8,The energy consumption (in kWh) for different ...,0.01,RBD,59 Household Appliance A Appliance B Appliance...,5,4
9,Performing these calculations for the machine ...,Insufficient Data,Insufficient Data,66 1 2 3 4 0 6.33 6.26 6.4...,8,4

In [6]:
df.iloc[9]
data_dict = {col: values for col, values in zip(
    df.iloc[9]['Data'].columns, df.iloc[9]['Data'].values.T)}
temp = pd.DataFrame(data_dict)
temp

      1     2     3     4
0  6.33  6.26  6.44  6.29
1  6.26  6.36  6.38  6.23
2  6.31  6.23  6.58  6.19
3  6.29  6.27  6.54  6.21
4   6.4  6.19  6.56   NaN
5   NaN   6.5  6.34   NaN
6   NaN  6.19  6.58   NaN
7   NaN  6.22   NaN   NaN

In [2]:
import pandas as pd

# Load the dataset
df = pd.read_csv('./dataset.csv')

# Fill missing values in 'Sr. No' column
df['Sr. No'] = df['Sr. No'].fillna(method='ffill')

# Group by 'Sr. No'
grouped_df = df.groupby('Sr. No')

# Required columns
required_columns = ['Data'] + [f'Unnamed: {i}' for i in range(3, 10)]

# Process each group
processed_groups = {}
for name, group in grouped_df:
    missing_columns = [
        col for col in required_columns if col not in group.columns]
    if missing_columns:
        print(f"Missing columns in group {name}: {missing_columns}")
        continue
    filtered_group = group[required_columns].copy()
    filtered_group.fillna('', inplace=True)
    processed_groups[name] = filtered_group

# Drop required columns from the original dataframe
df.drop(columns=required_columns, inplace=True)

# Create new dataframe with first entries from each group
new_df = df.groupby('Sr. No').first()

# Process each group to handle varying lengths of columns
for i in range(1, len(processed_groups) + 1):
    d = processed_groups[i].copy()
    new_columns = d.iloc[0]
    d.columns = new_columns
    d = d.drop(d.index[0])
    d.reset_index(drop=True, inplace=True)
    d.replace("", float("NaN"), inplace=True)

    # Remove all NaN columns
    d.dropna(how='all', axis=1, inplace=True)

    # Ensure to drop only fully NaN rows if they exist
    d.dropna(how='all', inplace=True)

    # Align columns by filling NaNs at the end
    d = d.apply(lambda x: pd.Series(x.dropna().values))

    # Assign the processed group back
    processed_groups[i] = d

# Assign the processed groups' values to the 'Data' column
new_df = new_df.assign(Data=list(processed_groups.values()))

# Reset index and drop 'Sr. No' column
df = new_df.reset_index().drop(columns='Sr. No')

df.head()

,Questions,Alpha,Type,Data
0,A researcher is studying the effect of differe...,0.05,CRD,0 Fertilizer A Fertilizer B Fertilizer C 0 ...
1,A company wants to compare customer satisfacti...,0.01,CRD,7 Model X Model Y Model Z 0 7 8 ...
2,To study the effect of three different diets o...,0.05,CRD,14 Diet A Diet B Diet C 0 5 4 ...
3,The preference scores (out of 10) for three di...,0.05,FD,21 Market Market Packaging A Packaging B P...
4,The productivity (in units) for employees usin...,0.05,FD,29 Shift Shift Tool A Tool B Tool C 0 ...

In [3]:
df['rows'] = df['Data'].apply(lambda x: x.shape[0])
df['columns'] = df['Data'].apply(lambda x: x.shape[1])
df.head(10)

,Questions,Alpha,Type,Data,rows,columns
0,A researcher is studying the effect of differe...,0.05,CRD,0 Fertilizer A Fertilizer B Fertilizer C 0 ...,5,3
1,A company wants to compare customer satisfacti...,0.01,CRD,7 Model X Model Y Model Z 0 7 8 ...,5,3
2,To study the effect of three different diets o...,0.05,CRD,14 Diet A Diet B Diet C 0 5 4 ...,5,3
3,The preference scores (out of 10) for three di...,0.05,FD,21 Market Market Packaging A Packaging B P...,6,5
4,The productivity (in units) for employees usin...,0.05,FD,29 Shift Shift Tool A Tool B Tool C 0 ...,6,5
5,The effectiveness scores (out of 10) of differ...,0.05,FD,37 Platform Platform Ad Type 1 Ad Type 2 Ad T...,6,5
6,The wear of tires from three different brands ...,0.01,RBD,45 Supplier Speed 20 mph Speed 40 mph Speed 60...,5,4
7,The crop yield (in tons) for three types of fe...,0.01,RBD,52 Soil Type Fertilizer A Fertilizer B Fertili...,5,4
8,The energy consumption (in kWh) for different ...,0.01,RBD,59 Household Appliance A Appliance B Appliance...,5,4
9,Performing these calculations for the machine ...,Insufficient Data,Insufficient Data,66 1 2 3 4 0 6.33 6.26 6.4...,8,4

In [4]:
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer('distilbert-base-nli-stsb-mean-tokens')

for i in range(len(df)):
    headers = df.iloc[i]['Data'].columns
    headers = [
        header.split()[0] if ' ' in header else header for header in headers]
    numeric_headers = [int(header) for header in headers if header.isdigit()]
    max_header = max(numeric_headers) if numeric_headers else None
    headers = [header if not header.isdigit() else str(max_header)
               for header in headers]
    header_embeddings = model.encode(headers)
    similarity_matrix = cosine_similarity(header_embeddings)
    np.fill_diagonal(similarity_matrix, 0)
    max_similarity = np.max(similarity_matrix, axis=1)
    distinct_entities = np.sum(max_similarity < 0.7)
    df.at[i, 'distinct_entities_count'] = distinct_entities + 1

c:\Users\bavis\AppData\Local\Programs\Python\Python311\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

In [5]:
df

,Questions,Alpha,Type,Data,rows,columns,distinct_entities_count
0,A researcher is studying the effect of differe...,0.05,CRD,0 Fertilizer A Fertilizer B Fertilizer C 0 ...,5,3,1.0
1,A company wants to compare customer satisfacti...,0.01,CRD,7 Model X Model Y Model Z 0 7 8 ...,5,3,1.0
2,To study the effect of three different diets o...,0.05,CRD,14 Diet A Diet B Diet C 0 5 4 ...,5,3,1.0
3,The preference scores (out of 10) for three di...,0.05,FD,21 Market Market Packaging A Packaging B P...,6,5,1.0
4,The productivity (in units) for employees usin...,0.05,FD,29 Shift Shift Tool A Tool B Tool C 0 ...,6,5,1.0
...,...,...,...,...,...,...,...
100,A company is testing the effectiveness of four...,None,FD,784 Customer Segment Customer Segment Channe...,6,7,2.0
101,A botanist is studying the effect of three dif...,None,RBD,792 Fertilizer Type Plant 1 Plant 2 Plant 3 Pl...,3,6,2.0
102,A pharmaceutical company is testing the effect...,None,RBD,797 Drug Type Patient 1 Patient 2 Patient 3 Pa...,3,6,2.0
103,An educational researcher is comparing the eff...,None,RBD,802 Teaching Method Student 1 Student 2 Studen...,3,6,2.0
104,A manufacturing company is evaluating the effi...,None,RBD,807 Machine Type Hour 1 Hour 2 Hour 3 Hour 4 H...,3,6,2.0

In [38]:

print(df.iloc[21]['Data'])
#Write it to a csv file
ndf = df.iloc[21]['Data']
ndf.to_csv('output.csv', index=False)

163        Treatment level
0    Block               1   1   2   3   4
1    Block               2  23  26  24  24
2    Block               3  31  35  32  33
3    Block               4  27  29  26  27
4    Block               5  21  28  27  22
5      NaN             NaN  18  25  27  20

In [7]:
df.shape

(105, 7)

In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = df[['columns', 'distinct_entities_count']]
y = df['Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier(random_state=42)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_test, y_pred)

0.8095238095238095

In [9]:
sample_num_cols = 6
sample_num_entities = 3

X_sample = [[sample_num_cols, sample_num_entities]]
y_sample = clf.predict(X_sample)[0]

print(f"Predicted type for sample data: {y_sample}")

Predicted type for sample data: RBD

c:\Users\bavis\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [10]:
df['isNested'] = False

for index, row in df.iterrows():
    sample = row['Data'].dropna(how='any')
    
    nested = True
    for i in range(len(sample)):
        if sample.iloc[i].iloc[0] != sample.iloc[0].iloc[0]:
            nested = False
            break

    if nested:
        df.at[index, 'isNested'] = True

In [31]:
df.iloc[35]

Questions                  Agricultural researchers are studying three di...
Alpha                                                                   0.01
Type                                                                     RBD
Data                       302 Block Method 1 Method 2 Method 3
0       1...
rows                                                                       6
columns                                                                    4
distinct_entities_count                                                  2.0
isNested                                                               False
Name: 35, dtype: object

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = df[['columns', 'distinct_entities_count', 'isNested']]
y = df['Type']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier(random_state=42)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_test, y_pred)

0.9523809523809523

In [13]:
import joblib

joblib.dump(clf, 'model.pkl')

['model.pkl']

In [14]:
import joblib 
model = joblib.load('model.pkl')

sample_num_cols = 6
sample_num_entities = 3
sample_is_nested = True

X_sample = [[sample_num_cols, sample_num_entities, sample_is_nested]]
y_sample = model.predict(X_sample)[0]


y_sample_proba = model.predict_proba(X_sample)
max_proba_index = y_sample_proba.argmax()
max_proba = y_sample_proba[0][max_proba_index]
predicted_class = model.classes_[max_proba_index]

print(f"Predicted type for sample data: {y_sample}")
print(f"with confidence: {max_proba}")

Predicted type for sample data: FD
with confidence: 0.75

c:\Users\bavis\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\bavis\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [15]:
import joblib

joblib.dump(clf, 'model.pkl')

['model.pkl']

In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = df[['columns', 'distinct_entities_count', 'isNested']]
y = df['Type']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier(random_state=42)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_test, y_pred)

import joblib

joblib.dump(clf, 'model.pkl')

     columns  distinct_entities_count  isNested
30         3                      2.0     False
65         4                      2.0     False
64         4                      2.0     False
53         4                      2.0     False
45         3                      1.0     False
94         7                      2.0      True
104        6                      2.0     False
47         3                      1.0     False
10         3                      2.0     False
0          3                      1.0     False
18         3                      4.0     False
31         6                      2.0      True
89         6                      2.0      True
96         7                      2.0      True
77         4                      2.0     False
4          5                      1.0      True
80         4                      2.0     False
33         6                      2.0      True
12         5                      1.0     False
26         6                      2.0      True
99         7                      2.0      True

['model.pkl']

In [32]:
import pandas as pd

test_data = [{'columns': 4, 'distinct_entities_count': 2, 'isNested': False}]
test_df = pd.DataFrame(test_data)

import joblib

# Load the trained model
model = joblib.load('model.pkl')
model.predict(test_df)

array(['RBD'], dtype=object)